### ISSUE TITLE
Visualization of output Mask

### ISSUE THREAD

**Issue by maryamag85** [nongnoochr/udacity_ai_for_healthcare_nanodegree#1]
Thanks for sharing your code, I have an issue visualization the output mask. Have you been able to do so? would you mind sharing your code for visualization of the 3D output mask? mine is in the numpy form and when I convert to nifti it shows as dashed area, not a whole consistent mask.

**Comment by nongnoochr** [comment]
Hi maryamag85,
I had some code to visualize 3D output mask in the notebook "[section1/Final%20Project%20EDA.ipynb](https://github.com/nongnoochr/udacity_ai_for_healthcare_nanodegree/blob/main/Project2_Hippocampal_Volume_Quantification_in_Alzheimer_Progression/section1/Final%20Project%20EDA.ipynb)" and mostly used [3D Slicer](https://www.slicer.org/) to help with the visualization.

HTH
